// Package decoder provides functionality to decode Manchester-encoded data signals from events
// generated by a Raspberry Pi (via GPIO events). It performs clock recovery and bit
// decoding asynchronously using Go's goroutines and channels, ensuring efficient handling
// of events and continuous data streams.
//
// The decoding process is divided into two main phases:
//  1. Clock recovery: unless a bit clock is configured, the decoder finds the bit period
//     in the incoming edges themselves and keeps following it, so it reads a sender of
//     any bit rate whose clock may be off or drift.
//  2. Data decoding: Once the clock is known, the decoder interprets incoming
//     event edges (rising and falling) as bits (High or Low) according to the Manchester encoding scheme.
//     It also handles timing tolerances to account for signal variations, ensuring robust decoding.
//
// Key features:
//   - Asynchronous event handling using goroutines to keep the main process responsive.
//   - Clock recovery from the edge timing alone, with no knowledge of the frame format.
//   - Robust bit decoding with tolerance handling to account for signal noise and timing
//     deviations.
//   - Graceful shutdown mechanism to properly close channels and wait for background tasks
//     to finish.
//
// The decoder reads rising and falling edges from the channel passed to New and
// delivers decoded bits (High/Low/Invalid) on the channel returned by Bits().
//
// # Example usage
//
//	func main() {
//	    // The decoder consumes its own Event type, so a transport that
//	    // reports edges differently needs a small translation step. With
//	    // gpio that is a goroutine feeding decoder.Event values:
//	    events := make(chan decoder.Event, 1024)
//	    go func() {
//	        defer close(events)
//	        for evt := range gpioEvents {
//	            var edge decoder.Edge
//	            switch evt.Edge {
//	            case gpio.RisingEdge:
//	                edge = decoder.RisingEdge
//	            case gpio.FallingEdge:
//	                edge = decoder.FallingEdge
//	            default:
//	                continue
//	            }
//	            events <- decoder.Event{Time: evt.Time, Edge: edge, Missed: evt.Missed}
//	        }
//	    }()
//
//	    // A bit clock of 0 recovers the clock from the signal.
//	    dec, err := decoder.New(events, 0,
//	        decoder.WithManchesterEncoding(decoder.IEEE),
//	    )
//	    if err != nil {
//	        log.Fatal(err)
//	    }
//	    defer dec.Close() // stops the decoder and waits for clean shutdown
//
//	    log.Println(dec.Info())
//
//	    for bit := range dec.Bits() {
//	        // bit is decoder.High, decoder.Low or decoder.Invalid
//	        _ = bit
//	    }
//	}
//
// # Framing
//
// The decoder delivers a raw bit stream and knows nothing about bytes: start
// and stop bits, sync preambles, byte boundaries and the polarity of the line
// are the caller's business.
//
// With a recovered clock (a bit clock of 0) the decoder buffers the edges until
// it knows both the clock and the bit phase, then decodes the buffer, so a
// transmission arrives in full once the first full-bit interval has passed.
// The clock locks on 16 intervals that show both the half-bit and the
// full-bit period; a stream of only identical or only alternating bits is
// ambiguous and never locks.
//
// With a configured bit clock the decoder does not buffer, and two properties
// matter when reading that stream:
//
//  1. Bits are decoded from the interval between two edges, so the very first
//     edge only establishes the reference timestamp and yields no bit. The
//     first bit of a transmission is therefore never reported.
//  2. A run of identical bits produces nothing but half-bit intervals, from
//     which the position of the mid-bit edge cannot be derived. The decoder
//     settles on the correct phase at the first full-bit interval, which is
//     the first place where the transmitted bit value changes.
//
// Both are covered by the sync bytes the encoder sends ahead of the data
// (see encoder.WithSyncBytes): the preamble absorbs the lost first bit, and
// the low start bit of the first data byte provides the full-bit interval
// that locks the phase. Senders that transmit without a preamble must expect
// to lose the beginning of every message.
package decoder

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"sync"
	"sync/atomic"
	"time"
)

// Edge represents a line state change (RisingEdge or FallingEdge)
type Edge uint8

// Bit represents a decoded Manchester bit
type Bit int

// Event represents a state change event (e.g., RisingEdge or FallingEdge).
//
// Missed is the number of edges lost immediately before this one - the
// counterpart of gpio.Event.Missed, plus whatever the caller itself had to
// drop. The decoder does not use the interval to an event with Missed > 0:
// clock recovery starts over from that event, while decoding it counts as an
// invalid interval.
type Event struct {
	Time   time.Time // Time is the exact time when the edge event was detected.
	Edge   Edge      // Edge indicates the type of state change (RisingEdge or FallingEdge).
	Missed uint64    // Missed is the number of edges lost immediately before this one.
}

// ManchesterEncoding represents the type of Manchester encoding to use.
type ManchesterEncoding int

type Option func(*Decoder)

const (
	FallingEdge Edge = 0 // FallingEdge represents a high → low transition
	RisingEdge  Edge = 1 // RisingEdge represents a low → high transition

	Low     Bit = 0  // Low represents a logical 0
	High    Bit = 1  // High represents a logical 1
	Invalid Bit = -1 // Invalid represents an invalid bit (e.g., due to timing errors)
)

const (
	IEEE ManchesterEncoding = iota
	Thomas
)

const (
	discoverClock = iota // Decoder state: clock recovery
	decodeData           // Decoder state: data decoding

	bitTimeTolerance = 25 // Percent tolerance for half/full bit timing
	invalidThreshold = 20 // Max consecutive invalid intervals before resync
)

// atomicDuration is a time.Duration that is safe for concurrent access.
type atomicDuration struct {
	v atomic.Int64
}

func (d *atomicDuration) Load() time.Duration   { return time.Duration(d.v.Load()) }
func (d *atomicDuration) Store(v time.Duration) { d.v.Store(int64(v)) }

// Decoder holds all state and channels for decoding Manchester signals
type Decoder struct {
	// state is the current state: clock recovery or data decoding.
	// It is atomic because Info() reports it from another goroutine.
	state atomic.Int32

	lastTimestamp   time.Time // Time of last event
	receivedHalfBit int       // Tracks first or second half of bit
	bufferSize      int       // Size of the output bit buffer (default 1024)

	// Clock recovery, see recovery.go.
	pending    []Event // Edges buffered while the clock or the bit phase is unknown
	tracking   bool    // The clock was recovered from the signal and follows it
	phaseKnown bool    // With a recovered clock: the bit phase is settled

	manchesterEncoding ManchesterEncoding // Type of Manchester encoding (e.g., IEEE vs. Thomas)
	decodingTable      [2]Bit             // Manchester decoding lookup table: [Level][Bit]

	// fullBitTime is the full bit period. It is atomic because Info() derives
	// the decoding frequency from it while the decoder is running.
	fullBitTime          atomicDuration
	halfBitTime          time.Duration // Half-bit period duration
	fullBitTimeTolerance time.Duration // Full bit period tolerance
	halfBitTimeTolerance time.Duration // Half-bit period tolerance
	invalidIntervalCount uint64        // Count of consecutive invalid events

	bufferOverflowCount atomic.Uint64 // Count of buffer overflows when sending bits
	resyncCount         atomic.Uint64 // Count of resynchronizations due to invalid intervals

	eventC <-chan Event // Input channel for GPIO events
	c      chan Bit     // Output channel for decoded bits

	wg     sync.WaitGroup
	cancel context.CancelFunc
	logger *slog.Logger // Optional logger for debugging and info
}

// New creates a new Decoder instance, initializes channels, and starts the decoding goroutine.
// Call Close() to stop the decoder and wait for a clean shutdown.
//
// bitClockHz selects how the bit timing is established:
//   - greater than zero: the bit periods are calculated from it directly and
//     clock recovery is skipped.
//   - zero: the bit clock is recovered from the incoming edges and followed
//     while the signal lasts, whatever the sender's bit rate. The first bits
//     are reported once 16 intervals have shown both half-bit and full-bit
//     periods, together with the bits buffered before.
//
// It returns an error if c is nil, if bitClockHz is negative, or if an
// unsupported Manchester encoding was selected.
//
// With a configured bit clock the first bit of a transmission is never
// reported; see the package documentation on framing.
func New(c <-chan Event, bitClockHz int, opts ...Option) (*Decoder, error) {
	if c == nil {
		return nil, errors.New("event channel must not be nil")
	}

	if bitClockHz < 0 {
		return nil, fmt.Errorf("bit clock must not be negative, got %d (use 0 for clock discovery)", bitClockHz)
	}

	d := &Decoder{
		eventC:     c,
		pending:    make([]Event, 0, maxPending),
		bufferSize: 1024,
	}
	d.state.Store(discoverClock)

	for _, opt := range opts {
		opt(d)
	}

	// validate manchesterEncoding after options are applied
	switch d.manchesterEncoding {
	case IEEE, Thomas:
		d.decodingTable = decodingTable(d.manchesterEncoding)
	default:
		return nil, fmt.Errorf("unsupported Manchester encoding: %v", d.manchesterEncoding)
	}

	d.c = make(chan Bit, d.bufferSize)
	if bitClockHz > 0 {
		// If a frequency is provided, calculate the expected bit periods and tolerances directly.
		fullBitTime := time.Duration(int64(time.Second) / int64(bitClockHz))
		d.fullBitTime.Store(fullBitTime)
		d.halfBitTime = fullBitTime / 2
		d.fullBitTimeTolerance = fullBitTime * bitTimeTolerance / 100
		d.halfBitTimeTolerance = d.halfBitTime * bitTimeTolerance / 100
		d.state.Store(decodeData) // Skip clock recovery if frequency is known
	}

	// Start the decoding process in a separate goroutine.

	ctx, cancel := context.WithCancel(context.Background())
	d.cancel = cancel
	d.wg.Add(1)
	go d.listenForEvents(ctx)
	return d, nil
}

func WithBufferSize(size int) Option {
	return func(d *Decoder) {
		if size > 0 {
			d.bufferSize = size
		}
	}
}

// WithManchesterEncoding sets the type of Manchester encoding (IEEE or Thomas).
// An invalid encoding will be rejected by New() with an error.
func WithManchesterEncoding(enc ManchesterEncoding) Option {
	return func(d *Decoder) {
		d.manchesterEncoding = enc
	}
}

// WithLogger sets an optional logger for debug output during decoding.
// If not set, no logging is performed.
func WithLogger(l *slog.Logger) Option {
	return func(d *Decoder) {
		d.logger = l
	}
}

// Close stops the decoder by cancelling the internal context, waits for the
// goroutine to finish, and closes the Bits() channel.
func (d *Decoder) Close() error {
	// shutdown is triggered by cancelling the context passed to New().
	// Close() waits until listenForEvents() has terminated.
	d.cancel()
	d.wg.Wait()
	return nil
}

// Bits returns a read-only channel on which decoded bits are delivered.
// The channel is closed when the decoder has shut down.
func (d *Decoder) Bits() <-chan Bit {
	return d.c
}

// Info returns a human-readable summary of the decoder's current state.
// It includes:
//   - The current decoder state (discovering clock or decoding data).
//   - The current decoding frequency in Hz (calculated from the full bit period).
//   - The number of buffer overflows encountered while sending decoded bits.
//   - The number of resynchronizations triggered due to invalid intervals.
//
// This function is safe to call from an external goroutine, as atomic counters
// are used for thread-safe access to buffer overflow and resync counts.
func (d *Decoder) Info() string {
	var state string
	var frequency float64

	switch s := d.state.Load(); s {
	case discoverClock:
		state = "discovering clock"
	case decodeData:
		state = "decoding data"
		if t := d.fullBitTime.Load(); t > 0 {
			frequency = 1 / t.Seconds()
		}
	default:
		state = fmt.Sprintf("unknown state %v", s)
	}

	info := fmt.Sprintf(
		"Decoder state: %v, "+
			"Frequency: %.2f Hz, "+
			"Buffer overflow count: %v, "+
			"Resync count: %v", state, frequency, d.bufferOverflowCount.Load(), d.resyncCount.Load())
	return info
}

// eventHandler processes a single GPIO event and decodes it into bits
//   - discoverClock:
//     the edges are buffered until the bit clock can be recovered from them (see recovery.go)
//   - decodeData:
//     the decoder checks if the time since the last event matches either a full bit period or a half bit period (with tolerance).
//     With a recovered clock it first settles the bit phase, and follows the clock with every valid interval.
//     decoding manchester code:  https://www.elektroniktutor.de/internet/codes.html
func (d *Decoder) eventHandler(event Event) {
	if event.Edge != RisingEdge && event.Edge != FallingEdge {
		return
	}

	switch d.state.Load() {
	case discoverClock:
		d.recoverClock(event)
		return
	case decodeData:
		if d.tracking && !d.phaseKnown {
			d.recoverPhase(event)
			return
		}
	default:
		d.resynchronize()
		return
	}

	if d.lastTimestamp.IsZero() {
		d.lastTimestamp = event.Time
		return
	}

	delta := event.Time.Sub(d.lastTimestamp)
	d.lastTimestamp = event.Time

	// An interval that spans lost edges matches nothing and is reported
	// as invalid below, however well its length happens to fit.
	if event.Missed == 0 && d.isFullBit(delta) {
		// full bit detected >> its' a 1 or 0 depending on the edge
		d.receivedHalfBit = 0
		d.invalidIntervalCount = 0
		if d.tracking {
			d.track(delta, true)
		}
		d.sendBit(d.decodingTable[event.Edge])
		if d.logger != nil {
			d.logger.Debug("full bit detected", "edge", d.decodingTable[event.Edge], "delta", delta.Microseconds())
		}
		return
	}

	if event.Missed == 0 && withinTolerance(delta, d.halfBitTime, d.halfBitTimeTolerance) {
		d.invalidIntervalCount = 0
		if d.tracking {
			d.track(delta, false)
		}
		if d.receivedHalfBit == 0 {
			// first half bit detected >> wait for next half bit
			d.receivedHalfBit = 1
			return
		}

		// second half bit detected >> it's a 1 or 0 depending on the edge
		d.receivedHalfBit = 0
		d.sendBit(d.decodingTable[event.Edge])
		if d.logger != nil {
			d.logger.Debug("half bit detected", "edge", d.decodingTable[event.Edge], "delta", delta.Microseconds())
		}
		return
	}

	d.invalidInterval(event, delta)
}

// invalidInterval reports an interval that matches neither bit period, or
// spans lost edges, and resynchronises after a run of them.
//
// With a recovered clock the phase is lost as well: the edge that ended the
// interval starts a new buffer, and the phase is settled again at the next
// full-bit interval. With a configured clock the decoder keeps pairing half
// bits as before.
func (d *Decoder) invalidInterval(event Event, delta time.Duration) {
	d.receivedHalfBit = 0
	d.invalidIntervalCount++
	d.sendBit(Invalid)
	if d.logger != nil {
		d.logger.Debug("invalid interval detected, sending invalid bit", "delta", delta.Microseconds(), "missed", event.Missed)
	}

	if d.invalidIntervalCount > invalidThreshold {
		d.resynchronize()
		return
	}

	if d.tracking {
		d.phaseKnown = false
		d.pending = append(d.pending[:0], event)
	}
}

// withinTolerance checks if value is within tolerance of reference
// This function helps ensure that events are close enough to the expected timing values (half or full bit period).
func withinTolerance(value, reference, tolerance time.Duration) bool {
	delta := value - reference
	if delta < 0 {
		delta = -delta
	}
	return delta <= tolerance
}

// sendBit sends a bit to the output channel with non-blocking behavior
func (d *Decoder) sendBit(bit Bit) {
	select {
	case d.c <- bit:
	default:
		d.bufferOverflowCount.Add(1)
	}
}

// resynchronize discards the current timing after too many invalid intervals
// and returns to clock recovery, also when the bit clock was configured.
func (d *Decoder) resynchronize() {

	d.resyncCount.Add(1)
	d.state.Store(discoverClock)
	d.pending = d.pending[:0] // reset the buffer without reallocating (keep capacity)
	d.phaseKnown = false
	d.invalidIntervalCount = 0
	d.receivedHalfBit = 0
	d.lastTimestamp = time.Time{} // reset timestamp to avoid stale delta calculation on next event
}

// listenForEvents listens for events from eventC and processes them asynchronously
func (d *Decoder) listenForEvents(ctx context.Context) {
	defer func() {
		close(d.c)
		d.wg.Done()
	}()

	for {
		select {
		case <-ctx.Done():
			return
		case evt, ok := <-d.eventC:
			if !ok {
				return // Exit if the buffer channel is closed
			}
			d.eventHandler(evt)
		}
	}
}

// decodingTable returns the Manchester decoding lookup table for the given encoding type.
// maps the mid-bit Edge event to the decoded Bit.
//
// The table must be the inverse of the encoder's encodingTable:
//   - IEEE 802.3 encodes a logical 1 as a low-to-high transition at mid-bit,
//     so a rising mid-bit edge decodes to High.
//   - G.E. Thomas uses the opposite convention.
func decodingTable(code ManchesterEncoding) [2]Bit {
	switch code {
	case Thomas:
		return [2]Bit{FallingEdge: High, RisingEdge: Low}
		// default IEEE
	default:
		return [2]Bit{FallingEdge: Low, RisingEdge: High}
	}
}
