// Package decoder provides functionality to decode Manchester-encoded data signals from events
// generated by a Raspberry Pi (via GPIO events). It performs clock synchronization and bit
// decoding asynchronously using Go's goroutines and channels, ensuring efficient handling
// of events and continuous data streams.
//
// The decoding process is divided into two main phases:
//  1. **Clock Discovery**: The package calculates the bit timing (bit period and half-bit period)
//     by analyzing a series of event samples, ensuring that data decoding starts with the correct timing.
//  2. **Data Decoding**: Once clock synchronization is achieved, the decoder interprets incoming
//     event edges (rising and falling) as bits (High or Low) according to the Manchester encoding scheme.
//     It also handles timing tolerances to account for signal variations, ensuring robust decoding.
//
// Key Features:
// - Asynchronous event handling using goroutines to keep the main process responsive.
// - Clock synchronization phase to determine the bit timing based on incoming event samples.
// - Robust bit decoding with tolerance handling to account for signal noise and timing deviations.
// - Graceful shutdown mechanism to properly close channels and wait for background tasks to finish.
//
// Channels:
//   - `C`: Outputs decoded bits (High/Low/Invalid).
//   - `eventC`: Receives GPIO events (rising and falling edges).
//
// Lifecycle:
//
//	The decoder runs until the context passed to New() is cancelled.
//	Call Close() after cancellation to wait for a clean shutdown.
package decoder

import (
	"context"
	"fmt"
	"log/slog"
	"sort"
	"sync/atomic"
	"time"
)

// Edge represents a line state change (RisingEdge or FallingEdge)
type Edge uint8

// Bit represents a decoded Manchester bit
type Bit int

// Event represents a state change event (e.g., RisingEdge or FallingEdge).
type Event struct {
	Time time.Time // Time is the exact time when the edge event was detected.
	Edge Edge      // Edge indicates the type of state change (RisingEdge or FallingEdge).
}

// ManchesterEncoding represents the type of Manchester encoding to use.
type ManchesterEncoding int

type Option func(*Decoder)

const (
	FallingEdge Edge = 0 // FallingEdge represents a high → low transition
	RisingEdge  Edge = 1 // RisingEdge represents a low → high transition

	Low     Bit = 0  // Low represents a logical 0
	High    Bit = 1  // High represents a logical 1
	Invalid Bit = -1 // Invalid represents an invalid bit (e.g., due to timing errors)
)

const (
	IEEE ManchesterEncoding = iota
	Thomas
)

const (
	discoverClock = iota // Decoder state: clock discovery
	decodeData           // Decoder state: data decoding

	clockEventSamples = 500 // Number of samples for clock calculation
	bitTimeTolerance  = 25  // Percent tolerance for half/full bit timing
	invalidThreshold  = 20  // Max consecutive invalid intervals before resync
)

// Decoder holds all state and channels for decoding Manchester signals
type Decoder struct {
	state int // Current state: clock discovery or data decoding

	clockEventSamples []time.Duration // Samples for clock discovery
	lastTimestamp     time.Time       // Time of last event
	receivedHalfBit   int             // Tracks first or second half of bit
	bufferSize        int             // Size of the output bit buffer (default 1024)

	manchesterEncoding ManchesterEncoding // Type of Manchester encoding (e.g., IEEE vs. Thomas)
	decodingTable      [2]Bit             // Manchester decoding lookup table: [Level][Bit]

	fullBitTime          time.Duration // Full bit period duration
	halfBitTime          time.Duration // Half-bit period duration
	fullBitTimeTolerance time.Duration // Full bit period tolerance
	halfBitTimeTolerance time.Duration // Half-bit period tolerance
	invalidIntervalCount uint64        // Count of consecutive invalid events

	bufferOverflowCount atomic.Uint64 // Count of buffer overflows when sending bits
	resyncCount         atomic.Uint64 // Count of resynchronizations due to invalid intervals

	C      chan Bit      // Output channel for decoded bits
	eventC chan Event    // Input channel for GPIO events
	done   chan struct{} // Stop signal channel
	logger *slog.Logger  // Optional logger for debugging and info
}

// New creates a new Decoder instance, initializes channels, and starts the decoding goroutine.
// The context controls the lifetime of the decoder - cancel it to stop decoding.
// If bitClockHz > 0, clock discovery is skipped and the bit periods are calculated directly.
// Call Close() after cancellation to wait for clean shutdown and release resources.
func New(ctx context.Context, c chan Event, bitClockHz int, opts ...Option) (*Decoder, error) {
	d := &Decoder{
		eventC:            c,
		done:              make(chan struct{}),
		clockEventSamples: make([]time.Duration, 0, clockEventSamples),
		state:             discoverClock,
		bufferSize:        1024,
	}

	for _, opt := range opts {
		opt(d)
	}

	// validate manchesterEncoding after options are applied
	switch d.manchesterEncoding {
	case IEEE, Thomas:
		d.decodingTable = decodingTable(d.manchesterEncoding)
	default:
		return nil, fmt.Errorf("unsupported Manchester encoding: %v", d.manchesterEncoding)
	}

	d.C = make(chan Bit, d.bufferSize)
	if bitClockHz > 0 {
		// If a frequency is provided, calculate the expected bit periods and tolerances directly.
		d.fullBitTime = time.Duration(int64(time.Second) / int64(bitClockHz))
		d.halfBitTime = d.fullBitTime / 2
		d.fullBitTimeTolerance = d.fullBitTime * bitTimeTolerance / 100
		d.halfBitTimeTolerance = d.halfBitTime * bitTimeTolerance / 100
		d.state = decodeData // Skip clock discovery if frequency is known
	}

	// Start the decoding process in a separate goroutine.
	go d.listenForEvents(ctx)
	return d, nil
}

func WithBufferSize(size int) Option {
	return func(d *Decoder) {
		if size > 0 {
			d.bufferSize = size
		}
	}
}

// WithManchesterEncoding sets the type of Manchester encoding (IEEE or Thomas).
// An invalid encoding will be rejected by New() with an error.
func WithManchesterEncoding(enc ManchesterEncoding) Option {
	return func(d *Decoder) {
		d.manchesterEncoding = enc
	}
}

// WithLogger sets an optional logger for debug output during decoding.
// If not set, no logging is performed.
func WithLogger(l *slog.Logger) Option {
	return func(d *Decoder) {
		d.logger = l
	}
}

// Close stops the decoder, waits for the goroutine, and closes output channels
func (d *Decoder) Close() error {
	// shutdown is triggered by cancelling the context passed to New().
	// Close() waits until listenForEvents() has terminated.
	<-d.done
	close(d.C)
	return nil
}

// Info returns a human-readable summary of the decoder's current state.
// It includes:
//   - The current decoder state (discovering clock or decoding data).
//   - The current decoding frequency in Hz (calculated from the full bit period).
//   - The number of buffer overflows encountered while sending decoded bits.
//   - The number of resynchronizations triggered due to invalid intervals.
//
// This function is safe to call from an external goroutine, as atomic counters
// are used for thread-safe access to buffer overflow and resync counts.
func (d *Decoder) Info() string {
	var state string
	var frequency float64

	switch s := d.state; s {
	case discoverClock:
		state = "discovering clock"
	case decodeData:
		state = "decoding data"
		if t := d.fullBitTime; t > 0 {
			frequency = 1 / t.Seconds()
		}
	default:
		state = fmt.Sprintf("unknown state %v", s)
	}

	info := fmt.Sprintf(
		"Decoder state: %v, "+
			"Frequency: %.2f Hz, "+
			"Buffer overflow count: %v, "+
			"Resync count: %v", state, frequency, d.bufferOverflowCount.Load(), d.resyncCount.Load())
	return info
}

// eventHandler processes a single GPIO event and decodes it into bits
//   - discoverClock:
//     the clock frequency is discovered by analyzing the bit periods (measuring full bit periods)
//   - decodeData:
//     the decoder checks if the time since the last event matches either a full bit period or a half bit period (with tolerance).
//     decoding manchester code:  https://www.elektroniktutor.de/internet/codes.html
func (d *Decoder) eventHandler(event Event) {
	if event.Edge != RisingEdge && event.Edge != FallingEdge {
		return
	}
	if d.lastTimestamp.IsZero() {
		d.lastTimestamp = event.Time
		return
	}

	delta := event.Time.Sub(d.lastTimestamp)
	d.lastTimestamp = event.Time

	switch d.state {
	case discoverClock:
		d.clockEventSamples = append(d.clockEventSamples, delta)

		// Once enough samples are gathered, calculate the bit periods.
		if len(d.clockEventSamples) >= clockEventSamples {
			half, full := calcBitPeriods(d.clockEventSamples)

			if full <= 0 || half <= 0 {
				d.resynchronize()
				return
			}

			d.halfBitTime = half
			d.fullBitTime = full
			d.halfBitTimeTolerance = d.halfBitTime * bitTimeTolerance / 100
			d.fullBitTimeTolerance = d.fullBitTime * bitTimeTolerance / 100
			d.clockEventSamples = nil
			d.receivedHalfBit = 0
			d.state = decodeData
		}

	case decodeData:
		if withinTolerance(delta, d.fullBitTime, d.fullBitTimeTolerance) {
			// full bit detected >> its' a 1 or 0 depending on the edge
			d.receivedHalfBit = 0
			d.invalidIntervalCount = 0
			d.sendBit(d.decodingTable[event.Edge])
			if d.logger != nil {
				d.logger.Debug("full bit detected", "edge", d.decodingTable[event.Edge], "delta", delta.Microseconds())
			}
			return
		}

		if withinTolerance(delta, d.halfBitTime, d.halfBitTimeTolerance) {
			d.invalidIntervalCount = 0
			if d.receivedHalfBit == 0 {
				// first half bit detected >> wait for next half bit
				d.receivedHalfBit = 1
				return
			}

			// second half bit detected >> it's a 1 or 0 depending on the edge
			d.receivedHalfBit = 0
			d.sendBit(d.decodingTable[event.Edge])
			if d.logger != nil {
				d.logger.Debug("half bit detected", "edge", d.decodingTable[event.Edge], "delta", delta.Microseconds())
			}
			return
		}

		d.receivedHalfBit = 0
		d.invalidIntervalCount++
		d.sendBit(Invalid)
		if d.logger != nil {
			d.logger.Debug("invalid interval detected, sending invalid bit", "delta", delta.Microseconds())
		}
		if d.invalidIntervalCount > invalidThreshold {
			d.resynchronize()
		}

	default:
		d.receivedHalfBit = 0
		d.lastTimestamp = time.Time{}
		d.state = discoverClock
	}
}

// calcBitPeriods calculates half and full bit periods from event samples using median analysis
// It uses statistical analysis (sorting and median calculation) to determine the bit timing.
func calcBitPeriods(samples []time.Duration) (time.Duration, time.Duration) {
	// Ensure that there are enough samples (at least half of eventSamples)
	if len(samples) < clockEventSamples/2 {
		return 0, 0
	}

	// Sort the samples to help identify the half-bit period (the first entry should be half-bit)
	sort.Slice(samples, func(i, j int) bool { return samples[i] < samples[j] })

	var halfBitPeriodMedian time.Duration
	var fullBitPeriodMedian time.Duration

	// Identify the median half-bit period and the corresponding full-bit period.
	// Start from sample index 30 to ensure there is enough data for accurate median calculation.
	for n := 30; n < len(samples); n++ {
		halfBitPeriodMedian = median(samples[:n-1])

		// If the sample is 150% of the half-bit period, it is a full-bit period
		if samples[n] > halfBitPeriodMedian+halfBitPeriodMedian/2 {
			fullBitPeriodMedian = median(samples[n:])
			break
		}
	}

	// Fallback: If no clear split was found, assume full bit is twice half bit
	if fullBitPeriodMedian == 0 {
		fullBitPeriodMedian = halfBitPeriodMedian * 2
	}

	return halfBitPeriodMedian, fullBitPeriodMedian
}

// median calculates the median of a sorted slice
func median(durations []time.Duration) time.Duration {
	n := len(durations)
	if n == 0 {
		return 0
	}
	if n%2 == 1 {
		return durations[n/2] // Return the middle element for an odd-length slice.
	}
	// Return the average of the two middle elements for an even-length slice.
	return (durations[n/2-1] + durations[n/2]) / 2
}

// withinTolerance checks if value is within tolerance of reference
// This function helps ensure that events are close enough to the expected timing values (half or full bit period).
func withinTolerance(value, reference, tolerance time.Duration) bool {
	delta := value - reference
	if delta < 0 {
		delta = -delta
	}
	return delta <= tolerance
}

// sendBit sends a bit to the output channel with non-blocking behavior
func (d *Decoder) sendBit(bit Bit) {
	select {
	case d.C <- bit:
	default:
		d.bufferOverflowCount.Add(1)
	}
}

// resynchronize resets the decoder state in case of too many invalid intervals
func (d *Decoder) resynchronize() {

	d.resyncCount.Add(1)
	d.state = discoverClock
	d.clockEventSamples = d.clockEventSamples[:0] // reset the slice without reallocating (keep capacity)
	d.invalidIntervalCount = 0
	d.receivedHalfBit = 0
	d.lastTimestamp = time.Time{} // reset timestamp to avoid stale delta calculation on next event
}

// listenForEvents listens for events from eventC and processes them asynchronously
func (d *Decoder) listenForEvents(ctx context.Context) {
	defer close(d.done)

	for {
		select {
		case <-ctx.Done():
			return
		case evt, ok := <-d.eventC:
			if !ok {
				return // Exit if the buffer channel is closed
			}
			d.eventHandler(evt)
		}
	}
}

// decodingTable returns the Manchester decoding lookup table for the given encoding type.
// maps Edge events to decoded Bits
func decodingTable(code ManchesterEncoding) [2]Bit {
	switch code {
	case Thomas:
		return [2]Bit{FallingEdge: Low, RisingEdge: High}
		// default IEEE
	default:
		return [2]Bit{FallingEdge: High, RisingEdge: Low}
	}
}
